
    drop table Administrador if exists;

    drop table Banco if exists;

    drop table Busqueda if exists;

    drop table CGP if exists;

    drop table Comuna if exists;

    drop table Coordenadas if exists;

    drop table DiaYHorarioDeAtencion if exists;

    drop table HorarioDeAtencion if exists;

    drop table HorariosDeAtencionPorDia if exists;

    drop table LimitesDeZona if exists;

    drop table LocalComercial if exists;

    drop table PalabrasClave if exists;

    drop table ParadaDeColectivo if exists;

    drop table PuntoDeInteres if exists;

    drop table PuntoDeInteresConServicios if exists;

    drop table PuntoDeInteresEncontrado if exists;

    drop table RangoDeHorario if exists;

    drop table RangosDeHorarioEnUnDia if exists;

    drop table Rubro if exists;

    drop table Servicio if exists;

    drop table ServicioDePuntoDeInteres if exists;

    drop table Usuario if exists;

    drop table Zona if exists;

    drop table ZonasDeCobertura if exists;

    drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;

    create table Administrador (
        id integer generated by default as identity,
        mail varchar(255),
        primary key (id)
    );

    create table Banco (
        id integer not null,
        horarioDeAtencionBancario_id integer,
        primary key (id)
    );

    create table Busqueda (
        id integer generated by default as identity,
        fechaDeBusqueda date,
        textoBuscado varchar(255),
        tiempoDeRespuesta double,
        usuario_id integer,
        primary key (id)
    );

    create table CGP (
        id integer not null,
        primary key (id)
    );

    create table Comuna (
        numero integer not null,
        nombre varchar(255),
        primary key (numero)
    );

    create table Coordenadas (
        id integer not null,
        latitud double,
        longitud double,
        primary key (id)
    );

    create table DiaYHorarioDeAtencion (
        id integer generated by default as identity,
        dia integer,
        primary key (id)
    );

    create table HorarioDeAtencion (
        id integer generated by default as identity,
        primary key (id)
    );

    create table HorariosDeAtencionPorDia (
        HorarioDeAtencion_id integer not null,
        DiaYHorarioDeAtencion_id integer not null,
        primary key (HorarioDeAtencion_id, DiaYHorarioDeAtencion_id)
    );

    create table LimitesDeZona (
        zona_id integer not null,
        coordenadas_id integer not null
    );

    create table LocalComercial (
        id integer not null,
        horarioDeAtencion_id integer,
        rubro_id integer,
        primary key (id)
    );

    create table PalabrasClave (
        PuntoDeInteres_id integer not null,
        palabrasClave varchar(255)
    );

    create table ParadaDeColectivo (
        id integer not null,
        primary key (id)
    );

    create table PuntoDeInteres (
        id integer generated by default as identity,
        nombre varchar(255),
        coordenadas integer,
        primary key (id)
    );

    create table PuntoDeInteresConServicios (
        id integer not null,
        primary key (id)
    );

    create table PuntoDeInteresEncontrado (
        Busqueda_id integer not null,
        puntosDeInteresEncontrados_id integer not null
    );

    create table RangoDeHorario (
        id integer generated by default as identity,
        horarioFin time,
        horarioInicio time,
        primary key (id)
    );

    create table RangosDeHorarioEnUnDia (
        DiaYHorarioDeAtencion_id integer not null,
        rangosDeHorario_id integer not null,
        primary key (DiaYHorarioDeAtencion_id, rangosDeHorario_id)
    );

    create table Rubro (
        id integer generated by default as identity,
        nombre varchar(255),
        radioDeCercania double,
        primary key (id)
    );

    create table Servicio (
        id integer not null,
        nombre varchar(255),
        horarioDeAtencion_id integer,
        primary key (id)
    );

    create table ServicioDePuntoDeInteres (
        PuntoDeInteresConServicios_id integer not null,
        servicio_id integer not null
    );

    create table Usuario (
        id integer generated by default as identity,
        nombre varchar(255),
        comuna_numero integer,
        coordenadas integer,
        primary key (id)
    );

    create table Zona (
        id integer not null,
        primary key (id)
    );

    create table ZonasDeCobertura (
        CGP_id integer not null,
        zona_id integer not null
    );

    alter table HorariosDeAtencionPorDia 
        add constraint UK_111i2r20y2sbvmvsfqj5xihcf unique (DiaYHorarioDeAtencion_id);

    alter table LimitesDeZona 
        add constraint UK_a7fxrfas1st5kef8imgy2ggmw unique (coordenadas_id);

    alter table RangosDeHorarioEnUnDia 
        add constraint UK_ea178qwccgtpmnknmas14ydpi unique (rangosDeHorario_id);

    alter table ServicioDePuntoDeInteres 
        add constraint UK_epdnqxbreii010xuwphtmbhpa unique (servicio_id);

    alter table ZonasDeCobertura 
        add constraint UK_6hnaawlmd1r9057hpp7b9kjlq unique (zona_id);

    alter table Banco 
        add constraint FK42vye67rbukblawx9d8iu5kt 
        foreign key (horarioDeAtencionBancario_id) 
        references HorarioDeAtencion;

    alter table Banco 
        add constraint FKr9a4t222gyy4kdx8l20n36mm7 
        foreign key (id) 
        references PuntoDeInteresConServicios;

    alter table Busqueda 
        add constraint FKtool8uwuw9vd6xwhqqrgsi2tu 
        foreign key (usuario_id) 
        references Usuario;

    alter table CGP 
        add constraint FKoyl211o89q61hxhcjcv4b8y1j 
        foreign key (id) 
        references PuntoDeInteresConServicios;

    alter table HorariosDeAtencionPorDia 
        add constraint FKelqteq0lu0t0uwsnkuweetjvu 
        foreign key (DiaYHorarioDeAtencion_id) 
        references DiaYHorarioDeAtencion;

    alter table HorariosDeAtencionPorDia 
        add constraint FKb14ti73k05x5tvj555c87ryci 
        foreign key (HorarioDeAtencion_id) 
        references HorarioDeAtencion;

    alter table LimitesDeZona 
        add constraint FKngc95awggr9jswss8ef7u8l1u 
        foreign key (coordenadas_id) 
        references Coordenadas;

    alter table LimitesDeZona 
        add constraint FKkx8x2g4g4nvgeq0kl4o7jq1ej 
        foreign key (zona_id) 
        references Zona;

    alter table LocalComercial 
        add constraint FKmcwy1e0sbss7drhqgvpjixcmt 
        foreign key (horarioDeAtencion_id) 
        references HorarioDeAtencion;

    alter table LocalComercial 
        add constraint FK4ixa2q4nmq2pkn2a9e9w06kpv 
        foreign key (rubro_id) 
        references Rubro;

    alter table LocalComercial 
        add constraint FKem0bvbqhfxt4ymx31x082jnf6 
        foreign key (id) 
        references PuntoDeInteres;

    alter table PalabrasClave 
        add constraint FKfuemml6q2ae9fun48m8p4qk0d 
        foreign key (PuntoDeInteres_id) 
        references PuntoDeInteres;

    alter table ParadaDeColectivo 
        add constraint FK49lc9je5rqxq427wi10xgx6p0 
        foreign key (id) 
        references PuntoDeInteres;

    alter table PuntoDeInteres 
        add constraint FKss8j2ch2objkgaaf0jugkbqb1 
        foreign key (coordenadas) 
        references Coordenadas;

    alter table PuntoDeInteresConServicios 
        add constraint FKc9lqen0s3avw5m3677qbwv8fq 
        foreign key (id) 
        references PuntoDeInteres;

    alter table PuntoDeInteresEncontrado 
        add constraint FK3x9ccay8qunahna6k4wlw6ome 
        foreign key (puntosDeInteresEncontrados_id) 
        references PuntoDeInteres;

    alter table PuntoDeInteresEncontrado 
        add constraint FKdind5p43l12oq1p7pvbc7ei00 
        foreign key (Busqueda_id) 
        references Busqueda;

    alter table RangosDeHorarioEnUnDia 
        add constraint FKfoi790riikprnu4pe8eqs3rfu 
        foreign key (rangosDeHorario_id) 
        references RangoDeHorario;

    alter table RangosDeHorarioEnUnDia 
        add constraint FK2t2d5e5xdysok3y4bdbqmliw1 
        foreign key (DiaYHorarioDeAtencion_id) 
        references DiaYHorarioDeAtencion;

    alter table Servicio 
        add constraint FK72or8mbsind0k06q26bweo1he 
        foreign key (horarioDeAtencion_id) 
        references HorarioDeAtencion;

    alter table ServicioDePuntoDeInteres 
        add constraint FKexe33ndj78l131o2m5tqxfp47 
        foreign key (servicio_id) 
        references Servicio;

    alter table ServicioDePuntoDeInteres 
        add constraint FK2a5auuy87l71au8g32ale007p 
        foreign key (PuntoDeInteresConServicios_id) 
        references PuntoDeInteresConServicios;

    alter table Usuario 
        add constraint FKb4q1bvk1a71ohciljh389i642 
        foreign key (comuna_numero) 
        references Comuna;

    alter table Usuario 
        add constraint FKgj2t9aixrjcrw8elwco0avb21 
        foreign key (coordenadas) 
        references Coordenadas;

    alter table ZonasDeCobertura 
        add constraint FKkmmm5i0iv4ougw3g5n9j9iome 
        foreign key (zona_id) 
        references Zona;

    alter table ZonasDeCobertura 
        add constraint FKfubcubvack15fa7s97n29bad4 
        foreign key (CGP_id) 
        references CGP;
