
    drop table Administrador if exists;

    drop table BusquedaObserver if exists;

    drop table Comuna if exists;

    drop table DiaYHorarioDeAtencion if exists;

    drop table HorarioDeAtencion if exists;

    drop table LimitesDeZonas if exists;

    drop table PalabrasClave if exists;

    drop table PuntoDeInteres if exists;

    drop table RangosDeHorariosPorDia if exists;

    drop table Rubro if exists;

    drop table Servicio if exists;

    drop table Terminal if exists;

    drop table Usuario if exists;

    drop table Zona if exists;

    drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;

    create table Administrador (
        mail varchar(255),
        id integer not null,
        primary key (id)
    );

    create table BusquedaObserver (
        TIPO_DE_OBSERVADOR_DE_BUSQUEDA varchar(31) not null,
        id integer not null,
        tiempoMaximoDeDemoraEnSegundos double,
        administradorAContactar_id integer,
        terminal_id integer,
        primary key (id)
    );

    create table Comuna (
        numero integer not null,
        nombre varchar(255),
        primary key (numero)
    );

    create table DiaYHorarioDeAtencion (
        id integer generated by default as identity,
        dia integer,
        horarioDeAtencion_id integer,
        primary key (id)
    );

    create table HorarioDeAtencion (
        id integer generated by default as identity,
        primary key (id)
    );

    create table LimitesDeZonas (
        Poligono_id integer not null,
        latitud double,
        longitud double
    );

    create table PalabrasClave (
        PuntoDeInteres_id integer not null,
        palabrasClave varchar(255)
    );

    create table PuntoDeInteres (
        TIPO_DE_POI varchar(31) not null,
        id integer generated by default as identity,
        latitud double,
        longitud double,
        direccion varchar(255),
        nombre varchar(255),
        horarioDeAtencion_id integer,
        rubro_id integer,
        primary key (id)
    );

    create table RangosDeHorariosPorDia (
        DiaYHorarioDeAtencion_id integer not null,
        horarioFin time,
        horarioInicio time
    );

    create table Rubro (
        id integer generated by default as identity,
        nombre varchar(255),
        radioDeCercania double,
        primary key (id)
    );

    create table Servicio (
        id integer not null,
        nombre varchar(255),
        horarioDeAtencion_id integer,
        puntoDeInteres_id integer,
        primary key (id)
    );

    create table Terminal (
        latitud double,
        longitud double,
        nombre varchar(255),
        id integer not null,
        comuna_numero integer,
        primary key (id)
    );

    create table Usuario (
        id integer not null,
        password varchar(255),
        usuario varchar(255),
        primary key (id)
    );

    create table Zona (
        id integer not null,
        cgp_id integer,
        primary key (id)
    );

    alter table Administrador 
        add constraint FK61htljkn2rhl5r8b02b31i3rr 
        foreign key (id) 
        references Usuario;

    alter table BusquedaObserver 
        add constraint FKir4pw9c6vmwmkj26t7emwulyy 
        foreign key (administradorAContactar_id) 
        references Administrador;

    alter table BusquedaObserver 
        add constraint FKrn6vswmvh2g8812mom72cu61g 
        foreign key (terminal_id) 
        references Terminal;

    alter table DiaYHorarioDeAtencion 
        add constraint FKtirxrkctn9r536lkyj5fykwib 
        foreign key (horarioDeAtencion_id) 
        references HorarioDeAtencion;

    alter table LimitesDeZonas 
        add constraint FKemxveaocatmglk8192nus2u12 
        foreign key (Poligono_id) 
        references Zona;

    alter table PalabrasClave 
        add constraint FKfuemml6q2ae9fun48m8p4qk0d 
        foreign key (PuntoDeInteres_id) 
        references PuntoDeInteres;

    alter table PuntoDeInteres 
        add constraint FKto6f1kyn72ilbylnrdyoqsf1g 
        foreign key (horarioDeAtencion_id) 
        references HorarioDeAtencion;

    alter table PuntoDeInteres 
        add constraint FKnpwfm8ff9xuh4xy4v1lhe8vyo 
        foreign key (rubro_id) 
        references Rubro;

    alter table RangosDeHorariosPorDia 
        add constraint FKfyb0qqs2h00rkw46n8r6eg3lh 
        foreign key (DiaYHorarioDeAtencion_id) 
        references DiaYHorarioDeAtencion;

    alter table Servicio 
        add constraint FK72or8mbsind0k06q26bweo1he 
        foreign key (horarioDeAtencion_id) 
        references HorarioDeAtencion;

    alter table Servicio 
        add constraint FKk7ejp3en5u0mkemac1avdoaph 
        foreign key (puntoDeInteres_id) 
        references PuntoDeInteres;

    alter table Terminal 
        add constraint FKa612mo9h2y6hcdyjxo9jcsnu0 
        foreign key (comuna_numero) 
        references Comuna;

    alter table Terminal 
        add constraint FK53qyurqn2iecmh92hrg17jhwe 
        foreign key (id) 
        references Usuario;

    alter table Zona 
        add constraint FKe71yb6onktohw1d3qna8ne03y 
        foreign key (cgp_id) 
        references PuntoDeInteres;
